[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
discord-flows = "0.2.0"
serde_json = "1.0.96"
tokio_wasi = { version = "1.25.0", features = ["rt", "macros"] }
