[package]
name = "discord-integration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
shuttle-runtime = "0.14.0"
shuttle-axum = "0.14.0"
shuttle-shared-db = { version = "0.14.0", features = ["postgres"] }

axum = "0.6.15"
tokio = "1.27.0"

sqlx = { version = "0.6.3", features = ["postgres"] }
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
reqwest = { version = "0.11.16", features = ["json"] }
once_cell = "1.17.1"
uuid = { version = "1.3.1", features = ["v4"] }
lru = "0.10.0"

serenity = "0.11.5"
